---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./clusters/staging
  prune: true
  wait: true
  retryInterval: 2m0s
