---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
  labels:
    environment: ${ENVIRONMENT}
    cluster: ${CLUSTER_NAME}
spec:
  interval: 10m0s
  timeout: ${RECONCILE_TIMEOUT}
  sourceRef:
    kind: GitRepository
    name: apps
  path: ./clusters/staging
  prune: true
  wait: false
  retryInterval: 2m0s
  dependsOn:
    - name: infra
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
        optional: false
