---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
  labels:
    environment: ${ENVIRONMENT}
    cluster: ${CLUSTER_NAME}
spec:
  interval: ${RECONCILE_INTERVAL}
  url: https://github.com/${GITHUB_ORG}/fleet-apps.git
  ref:
    # Use semver for production stability
    semver: ${APPS_REF}
  secretRef:
    name: flux-system
  ignore: |
    # exclude all
    /*
    # include clusters dir
    !/clusters
