---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
  labels:
    environment: ${ENVIRONMENT}
    cluster: ${CLUSTER_NAME}
spec:
  interval: 30m0s
  timeout: ${RECONCILE_TIMEOUT}
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./clusters/production
  prune: true
  wait: true
  retryInterval: 5m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
        optional: false
