---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-instance.yaml
  - gitrepository-infra.yaml
  - gitrepository-apps.yaml
  - kustomization-infra.yaml
  - kustomization-apps.yaml
